=== ryanmerolle/jsonschema_netaddr/test_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "ipv4_addresses": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4": "True"}
                ]
            }
        },
        "ipv4_private_addresses": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4": "True"},
                    {"private": "True"}
                ]
            }
        },
        "ipv4_public_addresses": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4": "True"},
                    {"public": "True"}
                ]
            }
        },
        "ipv4_multicast_addresses": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4": "True"},
                    {"multicast": "True"}
                ]
            }
        },
        "ipv4_addresses_wplen": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4WithPrefix": "True"}
                ]
            }
        },
        "ipv4_private_addresses_wplen": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4WithPrefix": "True"},
                    {"private": "True"}
                ]
            }
        },
        "ipv4_public_addresses_wplen": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4WithPrefix": "True"},
                    {"public": "True"}
                ]
            }
        },
        "ipv4_multicast_addresses_wplen": {
            "type": "array",
            "items": {
                "type": "string",
                "allOf": [
                    {"ipv4WithPrefix": "True"},
                    {"multicast": "True"}
                ]
            }
        }
    },
    "required": [
        "ipv4_addresses",
        "ipv4_private_addresses",
        "ipv4_public_addresses",
        "ipv4_multicast_addresses",
        "ipv4_addresses_wplen",
        "ipv4_private_addresses_wplen",
        "ipv4_public_addresses_wplen",
        "ipv4_multicast_addresses_wplen"
        ],
    "additionalProperties": "False"
}

=== ryanmerolle/jsonschema_netaddr/test_data.json
{
    "ipv4_addresses": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],
    "ipv4_private_addresses": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],
    "ipv4_public_addresses": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],
    "ipv4_multicast_addresses": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],

    "ipv4_addresses_wplen": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],
    "ipv4_private_addresses_wplen": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],
    "ipv4_public_addresses_wplen": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ],
    "ipv4_multicast_addresses_wplen": [
        "10.0.0.1",
        "10.0.0.1/32",
        "8.8.8.8",
        "100::1",
        "100::1/128"
    ]
}
